_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: 245e6388-93aa-4c08-bdce-19f10ceac9f4
name: 'Drush Site-Install'
mail: admin@example.com
slogan: ''
page:
  403: /node/3
  404: /node/2
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
