<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\webform\Entity\WebformSubmission;

/**
 * Implements hook_form_alter() to add custom validation to Webforms.
 */
function webform_access_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // \Drupal::logger('my_module')->notice('Form alter hook is called for form ID: ' . $form_id);
  if (strpos($form_id, 'webform_submission_') === 0) {
    $webform_id = str_replace('webform_submission_', '', $form_id);

    if ($webform_id === 'add_address') {
      $form['actions']['submit']['#submit'][] = 'my_module_webform_submit_handler';
    }
  }
}

/**
 * Custom submit handler to restrict multiple submissions.
 */
function my_module_webform_submit_handler(array &$form, FormStateInterface $form_state) {
  $current_user = \Drupal::currentUser();
  
  if ($current_user->isAuthenticated()) {
    $uid = $current_user->id();

    if ($uid) {
      $submission_ids = \Drupal::entityQuery('webform_submission')
        ->condition('webform_id', 'add_address') 
        ->condition('data.uid', $uid) 
        ->execute();

      if (!empty($submission_ids)) {
        // User has already submitted the form.
        \Drupal::messenger()->addMessage(t('You have already submitted this form.'), 'error');
        $form_state->setRebuild(TRUE);
        return;
      }
    }
  }
}
